#application: "olp-rdm-staging"
#application: "rdmprotocol-hrd"
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /(.*\.html)
  static_files: static/\1
  upload: static/.*\.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: /libs
  static_dir: static/libs

# default landing page
- url: /
  script: model_handler.model_application

# page handlers
- url: /(about|contact|disclaimer|tools)
  script: pages.app

- url: /tools/.*
  script: pages.app

# model handlers
- url: /model/.*
  script: model_handler.model_application

# product handlers
- url: /(controller|node|software|splitter)/.*
  script: product_handler.app

# pid handlers
- url: /pid/.*
  script: pid_handler.pid_application

# pid handlers
- url: /manufacturer/(list|display)
  script: manufacturer_handler.app

# incoming data
- url: /incoming/.*
  script: incoming_handler.incoming_application

# export handlers, deprecated, move most of these to /json/
- url: /(download|export_controllers|export_models|index_info|missing_models|model_info)
  script: export.export_application

# API handlers
- url: /api/(json|proto)/1/.*
  script: api.\1_v1.app

# Admin page
- url: /admin(/.*)?
  script: admin.app
  login: required

# Contrib page, like admin, but for contributors
- url: /contrib(/.*)?
  script: contrib.app
  login: required

- url: /tasks/(build_pid_responder_index|fetch_image|fetch_controller_image|fetch_product_image|rank_devices)
  script: tasks.tasks_application
  login: admin

builtins:
- appstats: on
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^trunk/.*$
- ^BUILD*$
- ^DEBUG*$
- ^compiler.jar*$
- ^(node_modules/.*)
- ^(js_src/.*)
- ^bower.json*$
- ^package.json*$
- ^Gruntfile.js*$
- ^(static/libs/angular-mocks/.*)
- ^(unit-test-js/.*)
