# -*- coding: utf-8 -*-
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# model_data.py
# Copyright (C) 2011 Simon Newton
# Data for the device models.

DEVICE_MODEL_DATA = {
  161: [{'device_model': 258,
         'model_description': 'SLAMMO',
         'product_category': 1289,
         'software_versions': {16909060: {'label': 'SLAMMO XC1 v0.01',
                                          'personalities': [{'description': '8-bit dimming only',
                                                             'index': 1,
                                                             'slot_count': 1},
                                                            {'description': '8-bit and vector',
                                                             'index': 2,
                                                             'slot_count': 2},
                                                            {'description': '16-bit dim and vector',
                                                             'index': 3,
                                                             'slot_count': 3},
                                                            {'description': '16-bit dim, vector and strobe',
                                                             'index': 4,
                                                             'slot_count': 4}],
                                          'sensors': [],
                                          'supported_parameters': [128,
                                                                   129,
                                                                   130,
                                                                   144,
                                                                   224,
                                                                   225,
                                                                   32768]}}}],
  2056: [{'device_model': 307,
          'model_description': 'Betapack3',
          'product_category': 1281,
          'software_versions': {1395798066: {'label': 'S202',
                                             'personalities': [],
                                             'sensor_count': 1,
                                             'supported_parameters': []}}}],
  9258: [{'device_model': 3,
          'model_description': 'EURODMX STROBE',
          'product_category': 257,
          'software_versions': {1: {'label': 'E00000001',
                                    'personalities': [{'description': 'd',
                                                       'index': 1,
                                                       'slot_count': 2},
                                                      {'description': 'dE2',
                                                       'index': 2,
                                                       'slot_count': 2},
                                                      {'description': 'dE4',
                                                       'index': 3,
                                                       'slot_count': 4},
                                                      {'description': 'H',
                                                       'index': 4,
                                                       'slot_count': 2},
                                                      {'description': 'A',
                                                       'index': 5,
                                                       'slot_count': 0},
                                                      {'description': 'AE2',
                                                       'index': 6,
                                                       'slot_count': 0},
                                                      {'description': 'AC1',
                                                       'index': 7,
                                                       'slot_count': 1},
                                                      {'description': 'AC3',
                                                       'index': 8,
                                                       'slot_count': 3},
                                                      {'description': 'AC4',
                                                       'index': 9,
                                                       'slot_count': 4},
                                                      {'description': 'SLF',
                                                       'index': 10,
                                                       'slot_count': 0}],
                                    'sensor_count': 4,
                                    'supported_parameters': []}}}],
  16716: [{'device_model': 13,
           'model_description': 'Rail-Tran',
           'product_category': 2048,
           'software_versions': {}}],
  19541: [{'device_model': 4,
           'model_description': 'CRMX Nova FX',
           'product_category': 2049,
           'software_versions': {131336: {'label': '2.1.8',
                                          'personalities': [{'description': 'Proxy disabled (SuperNova mode)',
                                                             'index': 1,
                                                             'slot_count': 0},
                                                            {'description': 'Proxy enabled',
                                                             'index': 2,
                                                             'slot_count': 0}],
                                          'sensors': [],
                                          'supported_parameters': [32,
                                                                   33025,
                                                                   33026,
                                                                   128,
                                                                   129,
                                                                   16,
                                                                   17,
                                                                   81,
                                                                   32768,
                                                                   224,
                                                                   225,
                                                                   130]}}},
          {'device_model': 257,
           'model_description': 'CRMX Nova TX2 RDM',
           'product_category': 2049,
           'software_versions': {131328: {'label': '2.1.0',
                                          'personalities': [{'description': 'Proxy disabled (SuperNova mode)',
                                                             'index': 1,
                                                             'slot_count': 0},
                                                            {'description': 'Proxy:no automatic discovery',
                                                             'index': 2,
                                                             'slot_count': 0},
                                                            {'description': 'Proxy:auto full discovery',
                                                             'index': 3,
                                                             'slot_count': 0},
                                                            {'description': 'Proxy:only incremental discovery',
                                                             'index': 4,
                                                             'slot_count': 0},
                                                            {'description': 'Proxy:full & inc. discovery',
                                                             'index': 5,
                                                             'slot_count': 0}],
                                          'sensors': [],
                                          'supported_parameters': [32,
                                                                   33025,
                                                                   33026,
                                                                   128,
                                                                   129,
                                                                   16,
                                                                   17,
                                                                   81,
                                                                   32768,
                                                                   224,
                                                                   225,
                                                                   130]}}},
          {'device_model': 4661,
           'model_description': 'DALI/DSI Interface',
           'product_category': 2050,
           'software_versions': {4: {'label': '1.1.3',
                                     'personalities': [{'description': 'DALI',
                                                        'index': 1,
                                                        'slot_count': 1},
                                                       {'description': 'DSI',
                                                        'index': 2,
                                                        'slot_count': 1},
                                                       {'description': 'Disabled',
                                                        'index': 3,
                                                        'slot_count': 0}],
                                     'sensors': [{'description': 'Proximity sensor',
                                                  'supports_recording': 0,
                                                  'type': 127}],
                                     'supported_parameters': [128,
                                                              129,
                                                              32,
                                                              224,
                                                              225,
                                                              32770,
                                                              32771,
                                                              130,
                                                              32768,
                                                              32769,
                                                              512,
                                                              513]}}}],
  18501: [{'device_model': 258,
           'model_description': 'StarLED Dimmer (rev C)',
           'product_category': 1289,
           'software_versions': {131081: {'label': 'v2.9r 03-Nov-08 22:51:03 c3.249',
                                          'personalities': [{'description': '4cct White Led',
                                                             'index': 1,
                                                             'slot_count': 4},
                                                            {'description': '3cct RBG Led',
                                                             'index': 2,
                                                             'slot_count': 9},
                                                            {'description': '3cct RGBMaster',
                                                             'index': 3,
                                                             'slot_count': 12},
                                                            {'description': '3cct RGB/Preset',
                                                             'index': 4,
                                                             'slot_count': 9}],
                                          'sensor_count': 6,
                                          'supported_parameters': []}}},
          {'device_model': 388,
           'model_description': 'Vari-DC Dimmer',
           'product_category': 1287,
           'software_versions': {65540: {'label': 'v1.4r 05-Jun-09 14:03:15 c4.093',
                                         'personalities': [{'description': 'CandlePSU',
                                                            'index': 1,
                                                            'slot_count': 2},
                                                           {'description': 'ELDriver',
                                                            'index': 2,
                                                            'slot_count': 2}],
                                         'sensor_count': 0,
                                         'supported_parameters': []}}},
          {'device_model': 777,
           'model_description': 'LEDController/4 24V',
           'product_category': 1289,
           'software_versions': {131074: {'label': 'v2.2r 13-May-08 17:54:32 c3.249',
                                          'personalities': [{'description': '4cct RGBW',
                                                             'index': 1,
                                                             'slot_count': 4},
                                                            {'description': '4cct RGBW Mstr',
                                                             'index': 2,
                                                             'slot_count': 5},
                                                            {'description': '3cct RGB',
                                                             'index': 3,
                                                             'slot_count': 3},
                                                            {'description': '3cct RGB Mstr',
                                                             'index': 4,
                                                             'slot_count': 4},
                                                            {'description': '6cct RGB',
                                                             'index': 5,
                                                             'slot_count': 6},
                                                            {'description': '6cct RGB Mstr',
                                                             'index': 6,
                                                             'slot_count': 8},
                                                            {'description': '1cct LED',
                                                             'index': 7,
                                                             'slot_count': 1}],
                                          'sensor_count': 2,
                                          'supported_parameters': []}}}],
  18771: [{'device_model': 64516,
           'model_description': 'Quad120W',
           'product_category': 1289,
           'software_versions': {19267923: {'label': 'Quad120W V1.53',
                                            'personalities': [{'description': '4 DMX Channels',
                                                               'index': 1,
                                                               'slot_count': 4},
                                                              {'description': 'All output chans have same',
                                                               'index': 2,
                                                               'slot_count': 1},
                                                              {'description': 'Custom',
                                                               'index': 3,
                                                               'slot_count': 4}],
                                            'sensor_count': 3,
                                            'supported_parameters': []}}}],
  19792: [{'device_model': 2,
           'model_description': 'MAC 101 CT',
           'product_category': 258,
           'software_versions': {932: {'label': 'MAC 101 CT 1.0.0',
                                       'personalities': [{'description': 'CT',
                                                          'index': 1,
                                                          'slot_count': 10}],
                                       'sensor_count': 0,
                                       'supported_parameters': []}}},
          {'device_model': 1300,
           'model_description': 'MAC 350 Entour',
           'product_category': 258,
           'software_versions': {85196800: {'label': 'MAC 350E 1.1.0',
                                            'personalities': [{'description': '8 Bit Mode',
                                                               'index': 1,
                                                               'slot_count': 14},
                                                              {'description': '16 Bit Mode',
                                                               'index': 2,
                                                               'slot_count': 17}],
                                            'sensor_count': 0,
                                            'supported_parameters': []}}}],
  20813: [{'device_model': 592,
           'model_description': 'QS250S',
           'product_category': 258,
           'software_versions': {1069314: {'label': 'QMxxx 3.16',
                                           'personalities': [{'description': 'Normal',
                                                              'index': 1,
                                                              'slot_count': 16},
                                                             {'description': 'Simple',
                                                              'index': 2,
                                                              'slot_count': 16}],
                                           'sensor_count': 2,
                                           'supported_parameters': []}}}],
  21075: [{'device_model': 4,
           'model_description': 'ColorWash 700 EAT',
           'software_versions': {}},
          {'device_model': 5,
           'model_description': 'ColorWash 750 AT Tugsten',
           'software_versions': {}},
          {'device_model': 6,
           'model_description': 'ColorSpot 700 EAT',
           'software_versions': {}},
          {'device_model': 7,
           'model_description': 'ColorWash2500 EAT',
           'software_versions': {}},
          {'device_model': 8,
           'model_description': 'ColorSpot 2500 EAT',
           'software_versions': {}},
          {'device_model': 9,
           'model_description': 'ColorWash 1200 AT',
           'software_versions': {}},
          {'device_model': 10,
           'model_description': 'ColorSpot 1200 AT',
           'software_versions': {}},
          {'device_model': 11,
           'model_description': 'ColorWash 575 AT',
           'software_versions': {}},
          {'device_model': 12,
           'model_description': 'ColorWash 575 Zoom AT',
           'software_versions': {}},
          {'device_model': 13,
           'model_description': 'ColorWash 575E AT',
           'software_versions': {}},
          {'device_model': 14,
           'model_description': 'ColorWash 575 Zoom EAT',
           'software_versions': {}},
          {'device_model': 15,
           'model_description': 'Color Wash 250',
           'software_versions': {}},
          {'device_model': 16,
           'model_description': 'DigiSpot 3000 DT',
           'software_versions': {}},
          {'device_model': 17,
           'model_description': 'DigiSpot 7000 DT',
           'software_versions': {}},
          {'device_model': 18,
           'model_description': 'RedWash3192',
           'software_versions': {}},
          {'device_model': 19,
           'model_description': 'RedMix3192 [CS48]',
           'software_versions': {}},
          {'device_model': 20,
           'model_description': 'RedStrobe3192',
           'software_versions': {}},
          {'device_model': 21,
           'model_description': 'RedFlash3192',
           'software_versions': {}},
          {'device_model': 22,
           'model_description': 'ColorMix 575 AT',
           'software_versions': {}},
          {'device_model': 31,
           'model_description': 'ArcPower 384 Rack-Mount',
           'software_versions': {}},
          {'device_model': 32,
           'model_description': 'RDM-communicator',
           'software_versions': {}},
          {'device_model': 33,
           'model_description': 'Robin 300 Spot',
           'software_versions': {}},
          {'device_model': 34,
           'model_description': 'Robin 300 Wash',
           'software_versions': {}},
          {'device_model': 35,
           'model_description': 'Robin 300 Plasma Spot',
           'software_versions': {}},
          {'device_model': 36,
           'model_description': 'CityScape48',
           'software_versions': {}},
          {'device_model': 37,
           'model_description': 'ArcSource396 RGBW',
           'software_versions': {}},
          {'device_model': 38,
           'model_description': 'Robin 300 Plasma Wash',
           'software_versions': {}},
          {'device_model': 39,
           'model_description': 'Robin 300 Beam',
           'software_versions': {}},
          {'device_model': 40,
           'model_description': 'ColorSpot 1200 EAT Profile',
           'software_versions': {}},
          {'device_model': 41,
           'model_description': 'ColorBeam 700 EAT',
           'software_versions': {}},
          {'device_model': 42,
           'model_description': 'ArcPad348Integral',
           'software_versions': {}},
          {'device_model': 43,
           'model_description': 'CityScape48 Single Colour',
           'software_versions': {}},
          {'device_model': 44,
           'model_description': 'ArcSource48 Single Colour',
           'software_versions': {}},
          {'device_model': 45,
           'model_description': 'CitySource96 RGBW',
           'software_versions': {}},
          {'device_model': 46,
           'model_description': 'CitySource48 SmartWhite',
           'software_versions': {}},
          {'device_model': 47,
           'model_description': 'CityScape96 SmartWhite',
           'software_versions': {}},
          {'device_model': 48,
           'model_description': 'ArcSource48 SmartWhite',
           'software_versions': {}},
          {'device_model': 49,
           'model_description': 'ArcSource96 SmartWhite',
           'software_versions': {}},
          {'device_model': 50,
           'model_description': 'CityScape Extreme',
           'software_versions': {}},
          {'device_model': 51,
           'model_description': 'CitySource96 Single Colour',
           'software_versions': {}},
          {'device_model': 52,
           'model_description': 'ArcSource96 Single Colour',
           'software_versions': {}},
          {'device_model': 53,
           'model_description': 'ArcPad Extreme',
           'software_versions': {}},
          {'device_model': 54,
           'model_description': 'Robin 300 Spot Classic',
           'software_versions': {}},
          {'device_model': 55,
           'model_description': 'Robin 300 Beam Classic',
           'software_versions': {}},
          {'device_model': 56,
           'model_description': 'Robin 300 Wash Classic',
           'software_versions': {}},
          {'device_model': 57,
           'model_description': 'Robin 600 Spot',
           'software_versions': {}},
          {'device_model': 58,
           'model_description': 'Robin 600 Wash',
           'software_versions': {}},
          {'device_model': 59,
           'model_description': 'Robin 600 Beam',
           'software_versions': {}},
          {'device_model': 60,
           'model_description': 'Robin 600 Plasma Spot',
           'software_versions': {}},
          {'device_model': 61,
           'model_description': 'Robin 600 Plasma Wash',
           'software_versions': {}},
          {'device_model': 62,
           'model_description': 'Led Driver 360',
           'software_versions': {}},
          {'device_model': 63,
           'model_description': 'Color Beam 2500 EAT',
           'software_versions': {}},
          {'device_model': 64,
           'model_description': 'ArcPad48IntegralAWCW',
           'software_versions': {}},
          {'device_model': 65,
           'model_description': 'CS348_A3W',
           'software_versions': {}},
          {'device_model': 66,
           'model_description': 'ArcPower 12x16',
           'software_versions': {}},
          {'device_model': 67,
           'model_description': 'CityScape Extreme Half',
           'software_versions': {}},
          {'device_model': 68,
           'model_description': 'ArcPad Extreme Half',
           'software_versions': {}},
          {'device_model': 69,
           'model_description': 'DigiSpot 3000II DT',
           'software_versions': {}},
          {'device_model': 72,
           'model_description': 'Robe Media Server',
           'software_versions': {}},
          {'device_model': 73,
           'model_description': 'ArcPad 94 EPS',
           'software_versions': {}},
          {'device_model': 74,
           'model_description': 'ArcPad Integral 12',
           'software_versions': {}},
          {'device_model': 75,
           'model_description': 'Robin MMX Spot',
           'software_versions': {}},
          {'device_model': 76,
           'model_description': 'Robin 600 LEDWash White',
           'software_versions': {}},
          {'device_model': 77,
           'model_description': 'DigiSpot 3500 DT',
           'software_versions': {}},
          {'device_model': 78,
           'model_description': 'Robin 600 LEDWash SmartWhite',
           'product_category': 256,
           'software_versions': {10: {'label': 'Sw.ver. 1.0',
                                      'personalities': [{'description': 'Mode 1',
                                                         'index': 1,
                                                         'slot_count': 24},
                                                        {'description': 'Mode 2',
                                                         'index': 2,
                                                         'slot_count': 16},
                                                        {'description': 'Mode 3',
                                                         'index': 3,
                                                         'slot_count': 12},
                                                        {'description': 'Mode 4',
                                                         'index': 4,
                                                         'slot_count': 10},
                                                        {'description': 'Mode 5',
                                                         'index': 5,
                                                         'slot_count': 0}],
                                      'sensor_count': 2,
                                      'supported_parameters': []}}},
          {'device_model': 78,
           'model_description': 'Robin 600 LEDWash SmartWhite',
           'software_versions': {}},
          {'device_model': 79,
           'model_description': 'CityFlex CL',
           'software_versions': {}},
          {'device_model': 80,
           'model_description': 'ArcPad Extreme Single Colour',
           'software_versions': {}},
          {'device_model': 81,
           'model_description': 'ArcPad 94 Extreme Single Colour',
           'software_versions': {}},
          {'device_model': 82,
           'model_description': 'ArcPower 48 MC',
           'software_versions': {}},
          {'device_model': 83,
           'model_description': 'CityFlex novy',
           'software_versions': {}},
          {'device_model': 84,
           'model_description': 'Robin 1200 LEDWash',
           'software_versions': {}},
          {'device_model': 85,
           'model_description': 'Robin DLX Spot',
           'software_versions': {}},
          {'device_model': 86,
           'model_description': 'Robin DLX Wash',
           'software_versions': {}},
          {'device_model': 87,
           'model_description': 'Robin Sniper',
           'software_versions': {}},
          {'device_model': 88,
           'model_description': 'CityLine',
           'software_versions': {}},
          {'device_model': 89,
           'model_description': 'ArcPower 4x48 MC',
           'software_versions': {}},
          {'device_model': 117,
           'model_description': 'Robin 300 LEDWash',
           'software_versions': {}},
          {'device_model': 118,
           'model_description': 'Robin 600 LEDWash',
           'product_category': 256,
           'software_versions': {22: {'label': 'Sw.ver. 2.2',
                                      'personalities': [{'description': 'Mode 1',
                                                         'index': 1,
                                                         'slot_count': 37},
                                                        {'description': 'Mode 2',
                                                         'index': 2,
                                                         'slot_count': 21},
                                                        {'description': 'Mode 3',
                                                         'index': 3,
                                                         'slot_count': 15},
                                                        {'description': 'Mode 4',
                                                         'index': 4,
                                                         'slot_count': 10},
                                                        {'description': 'Mode 5',
                                                         'index': 5,
                                                         'slot_count': 0}],
                                      'sensor_count': 2,
                                      'supported_parameters': []}}}],
  21324: [{'device_model': 13828,
           'model_description': '3604PWM CV DRIVER Interface',
           'product_category': 1289,
           'software_versions': {33816835: {'label': 'SW Mk 1.3  RDM Mk 2.4 ',
                                            'personalities': [{'description': '',
                                                               'index': 1,
                                                               'slot_count': 4},
                                                              {'description': '',
                                                               'index': 2,
                                                               'slot_count': 5},
                                                              {'description': '',
                                                               'index': 3,
                                                               'slot_count': 2},
                                                              {'description': '',
                                                               'index': 4,
                                                               'slot_count': 1}],
                                            'sensors': [{'description': '  Power Supply Volts           ',
                                                         'supports_recording': 0,
                                                         'type': 1}],
                                            'supported_parameters': [21,
                                                                     32,
                                                                     48,
                                                                     49,
                                                                     80,
                                                                     81,
                                                                     96,
                                                                     112,
                                                                     128,
                                                                     129,
                                                                     130,
                                                                     144,
                                                                     192,
                                                                     224,
                                                                     225,
                                                                     240,
                                                                     1024,
                                                                     1029,
                                                                     288,
                                                                     289,
                                                                     290,
                                                                     769,
                                                                     833,
                                                                     4096,
                                                                     4097,
                                                                     4112,
                                                                     512,
                                                                     513,
                                                                     33009]}}}],
  21580: [{'device_model': 1,
           'model_description': 'DEC3 Enclosure Control',
           'product_category': 1536,
           'software_versions': {33: {'label': 'Main2.1 and UI2.1',
                                      'personalities': [{'description': 'RDM Monitoring',
                                                         'index': 1,
                                                         'slot_count': 0},
                                                        {'description': 'DMX Lamp Relay Enable',
                                                         'index': 2,
                                                         'slot_count': 1},
                                                        {'description': 'DMX Lamp Fan Heater Rly Enable',
                                                         'index': 3,
                                                         'slot_count': 3}],
                                      'sensor_count': 3,
                                      'supported_parameters': []}}},
          {'device_model': 3,
           'model_description': 'DEC3-MK2 Controller',
           'product_category': 1536,
           'software_versions': {85: {'label': '00.13',
                                      'personalities': [{'description': 'Monitor Mode',
                                                         'index': 1,
                                                         'slot_count': 0},
                                                        {'description': 'Control Mode',
                                                         'index': 2,
                                                         'slot_count': 1},
                                                        {'description': 'Service Mode',
                                                         'index': 3,
                                                         'slot_count': 3}],
                                      'sensor_count': 4,
                                      'supported_parameters': []}}}],
  22355: [{'device_model': 1,
           'model_description': 'W-RDM transmitter',
           'product_category': 257,
           'software_versions': {5505282: {'label': 'Micro RDM T1.6.7',
                                           'personalities': [],
                                           'sensor_count': 0,
                                           'supported_parameters': []}}}],
#          {'device_model': 1,
#           'product_category': 258,
#           'software_versions': {'5570818': {'label': 'Pico RDM U1.6.5',
#                                             'personalities': [],
#                                             'sensor_count': 0,
#                                             'supported_parameters': []}}}],
  25444: [{'device_model': 7882,
           'model_description': '788-LD+ Quad Dimmer Pack v2',
           'product_category': 1281,
           'software_versions': {1296: {'label': '788-LD+ v5.10',
                                        'personalities': [{'description': '8-bit',
                                                           'index': 1,
                                                           'slot_count': 8},
                                                          {'description': '16-bit',
                                                           'index': 2,
                                                           'slot_count': 8}],
                                        'sensor_count': 1,
                                        'supported_parameters': []}}}],
  25972: [{'device_model': 265,
           'model_description': 'Desire Vivid 40',
           'product_category': 257,
           'software_versions': {16908292: {'label': '1.2.0.0.0.04',
                                            'personalities': [{'description': 'Direct',
                                                               'index': 1,
                                                               'slot_count': 9},
                                                              {'description': 'HSI',
                                                               'index': 2,
                                                               'slot_count': 5},
                                                              {'description': 'HSI Plus 7',
                                                               'index': 3,
                                                               'slot_count': 14},
                                                              {'description': 'HSIC',
                                                               'index': 4,
                                                               'slot_count': 6},
                                                              {'description': 'HSIC Plus 7',
                                                               'index': 5,
                                                               'slot_count': 14},
                                                              {'description': 'RGB',
                                                               'index': 6,
                                                               'slot_count': 5},
                                                              {'description': 'RGB Plus 7',
                                                               'index': 7,
                                                               'slot_count': 14},
                                                              {'description': 'Studio',
                                                               'index': 8,
                                                               'slot_count': 5},
                                                              {'description': 'Studio Plus 7',
                                                               'index': 9,
                                                               'slot_count': 14}],
                                            'sensor_count': 9,
                                            'supported_parameters': []}}}],
  26724: [{'device_model': 1,
           'model_description': 'DMX-TRI MK1',
           'product_category': 2050,
           'software_versions': {1596: {'label': '00.05.007',
                                        'personalities': [],
                                        'sensors': [],
                                        'supported_parameters': [128,
                                                                 129,
                                                                 130,
                                                                 240]}}}],
  31344: [{'device_model': 1,
           'model_description': 'Dummy Model',
           'product_category': 32767,
           'software_versions': {1: {'label': 'Dummy Software Version',
                                     'personalities': [{'description': 'Personality 1',
                                                        'index': 1,
                                                        'slot_count': 5},
                                                       {'description': 'Personality 2',
                                                        'index': 2,
                                                        'slot_count': 10},
                                                       {'description': 'Personality 3',
                                                        'index': 3,
                                                        'slot_count': 20}],
                                     'sensors': [],
                                     'supported_parameters': [130,
                                                              144,
                                                              128,
                                                              224,
                                                              225,
                                                              129,
                                                              112,
                                                              1026,
                                                              1539]}}},
          {'device_model': 2,
           'model_description': 'Arduino RGB Mixer',
           'product_category': 1288,
           'software_versions': {1: {'label': '1.0',
                                     'personalities': [{'description': '6x PWM',
                                                        'index': 1,
                                                        'slot_count': 6},
                                                       {'description': '3x inverted PWM, 3x PWM',
                                                        'index': 2,
                                                        'slot_count': 6},
                                                       {'description': '6x inverted PWM',
                                                        'index': 3,
                                                        'slot_count': 6}],
                                     'sensors': [{'description': 'Case Temperature',
                                                  'supports_recording': 1,
                                                  'type': 0}],
                                     'supported_parameters': [112,
                                                              128,
                                                              129,
                                                              130,
                                                              160,
                                                              176,
                                                              224,
                                                              225,
                                                              512,
                                                              513,
                                                              514,
                                                              1029,
                                                              32768]}}}],
}
