name: Testing

on: [push, pull_request]

jobs:
  run_action:
    name: Test run action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: peternewman/actions-codespell@master
