name: Testing

on: [push, pull_request]

jobs:
  run_action:
    name: Test run action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: codespell-project/actions-codespell@master
      with:
        check_filenames: 1
        check_hidden: 1   
        exclude_file: .codespellignore
